### ISSUE TITLE
Failing to parse multi-line CMD properly

### ISSUE THREAD

**Issue by hairyhenderson** [RedCoolBeans/dockerlint#25]
### Issue details

`dockerlint` gives an error "No closing bracket found" given this _valid_ instruction:

```docker
CMD ["foo",\
  "bar"]
```

### Steps to reproduce/test case

Try to lint a `Dockerfile` with a multi-line `CMD` instruction...

### Affected version(s)

0.2.0, as used inside `linter-docker` in Atom

**Comment by rnagy** [comment]
Hii

This issue has been fixed.

**Comment by hairyhenderson** [comment]
Thanks @rnagy!

**Comment by hairyhenderson** [comment]
@rnagy will a 0.2.2 version be published to npmjs.com?

**Comment by rnagy** [comment]
@hairyhenderson we have published the latest release on npmjs.com
