### ISSUE TITLE
Custom Rules

### ISSUE THREAD

**Issue by soumypau1** [RedCoolBeans/dockerlint#28]
### Issue details

Hi Team,

I wanted to understand if there is a way to add my custom rules without having to write any code ? 
Is there any configuration file maintained where rules can be added/modified/removed?

-Soumyadeep

**Comment by rnagy** [comment]
Hello

There is no support for a configuration file and we don't plan it at the moment,
but if you would like to hack on it, please do so, we are open to submissions.
