### ISSUE TITLE
undefined ARG or ENV variable when using variables from base image

### ISSUE THREAD

**Issue by EvgenyOrekhov** [RedCoolBeans/dockerlint#49]
### Issue details

I am using an ENV variable that is defined in the base image, dockerlint doesn't like it:

> ERROR: RUN contains undefined ARG or ENV variable on line 3

That variable is defined in the base image specifically for using it in descendant images.

How do I tell dockerlint that that ENV variable is defined?

### Steps to reproduce/test case

```dockerfile
FROM php:fpm-alpine

RUN apk add --no-cache $PHPIZE_DEPS \
    && pecl install ast \
    && docker-php-ext-enable ast \
    && apk del $PHPIZE_DEPS
```

### Affected version(s)

Latest redcoolbeans/dockerlint Docker image.

**Comment by shah1raj** [comment]
I have the same issue.
Mount the Dockerfile into a container that will run Dockerlint: https://github.com/RedCoolBeans/dockerlint
Unable to find image 'redcoolbeans/dockerlint:latest' locally
latest: Pulling from redcoolbeans/dockerlint
81033e7c1d6a: Pulling fs layer
53d0e93b7cbb: Pulling fs layer
c37c5e27002a: Pulling fs layer
91a2998ae754: Pulling fs layer
91a2998ae754: Waiting
c37c5e27002a: Download complete
81033e7c1d6a: Verifying Checksum
81033e7c1d6a: Download complete
53d0e93b7cbb: Verifying Checksum
53d0e93b7cbb: Download complete
91a2998ae754: Verifying Checksum
91a2998ae754: Download complete
81033e7c1d6a: Pull complete
81033e7c1d6a: Pull complete
53d0e93b7cbb: Pull complete
53d0e93b7cbb: Pull complete
c37c5e27002a: Pull complete
c37c5e27002a: Pull complete
91a2998ae754: Pull complete
91a2998ae754: Pull complete
Digest: sha256:d18bd8f003e2b4e7ab13df3180a6efdd4aa6deca69ae557562a36533d6867061
Status: Downloaded newer image for redcoolbeans/dockerlint:latest
ERROR: RUN contains undefined ARG or ENV variable on line 32
ERROR: /jenkins_slave_home/DOA/Labs/Module6_Docker/Static_Code_Analysis/Dockerfile failed.

Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
Archiving artifacts
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Finished: FAILURE

Line 32 of dockerfile is as below:
RUN set -ex \
	&& for key in \
		05AB33110949707C93A279E3D3EFE6B686867BA6 \
		07E48665A34DCAFAE522E5E6266191C37C037D42 \
		47309207D818FFD8DCD3F83F1931D684307A10A5 \
		541FBE7D8F78B25E055DDEE13C370389288584E7 \
		61B832AC2F1C5A90F0F9B00A1C506407564C17A3 \
		79F7026C690BAA50B92CD8B66A3AD3F4F22C4FED \
		9BA44C2621385CB966EBA586F72C284D731FABEE \
		A27677289986DB50844682F8ACB77FC2E86E29AC \
		A9C5DF4D22E99998D9875A5110C01C5A2F6059E7 \
		DCFD35E0BF8CA7344752DE8B6FB21E8933C60243 \
		F3A04C595DB5B6A5F1ECA43E3B7BBB100D811BBE \
		F7DA48BB64BCB84ECBA7EE6935CD23C10D498E23 \
	; do \
		gpg --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
	done

Can someone help?
Thanks

**Comment by reinerj** [comment]
We will provide a fix shortly

**Comment by Spritekin** [comment]
I tried the latest docker image for redcoolbeans/dockerlint and got the same message today. So we are running 0.2 for now until fixed as it seems to ignore this problem.

**Comment by reinerj** [comment]
It will get fixed soon. we are very busy with work but i hope until net week it will be ready

**Comment by sbkg0002** [comment]
Any update?

**Comment by ssemichev** [comment]
Will be nice to fix it
