### ISSUE TITLE
Check for absolute WORKDIR should resolve variables

### ISSUE THREAD

**Issue by aCandidMind** [RedCoolBeans/dockerlint#9]
I have received the following error with $INSTALLPATH set to /app
`ERROR: WORKDIR path $INSTALLPATH must be absolute on line 20`

$INSTALLPATH was set via ENV like this
`ENV INSTALLPATH /app`

The check should resolve environment variables.

**Comment by jasperla** [comment]
Good point. Currently the parser doesn't build up an environment to re-use. Not only the `WORKDIR` check can use this, but others as well. It'll be a rather larger change so I cannot give an ETA yet, but it's certainly something I want to have too :)
